name: Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install
# TODO: RYAN - uncomment once tests are added
#      - name: Run tests
#        run: npm run test

      - name: Build package
        run: npm run build.lib

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: swift-layout
          path: dist/swift-layout

# TODO: RYAN - uncomment once we are ready to deploy & have tokens set up
#      - name: Deploy
#        if: success()
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: dist/angular-github-actions
#          enable_jekyll: true
